# Enable "Allow chat colors" in the Resource Packs plugin.

[opaque]
public_chat=0x17151A
public_chat_highlight=0x000000
private_message_sent=0x5A236D
private_message_sent_highlight=0x351040
private_message_received=0x4E285E
private_message_received_highlight=0x301038
friends_chat_info=0x493160
clan_chat_info_highlight=0x2E173D
clan_chat_message=0x543464
clan_chat_message_highlight=0x32163D
clan_info=0x4B315B
clan_info_highlight=0x2F1839
clan_message=0x52335F
clan_message_highlight=0x32173B
clan_guest_info=0x5B4A64
clan_guest_info_highlight=0x3E3046
clan_guest_message=0x59485F
clan_chat_guest_message_highlight=0x3B2D41
autochat_message=0x3B3835
autochat_message_highlight=0x171513
trade_chat_message=0x9A202B
trade_chat_message_highlight=0x69131B
server_message=0xB01828
server_message_highlight=0x79101C
game_message=0x26731F
game_message_highlight=0x174D13
examine=0x302D2A
examine_highlight=0x11100F
filtered=0x625E59
filtered_highlight=0x3D3936
username=0x171513
private_usernames=0x512062
clan_channel_name=0x4D315C
clan_chat_channel_name=0x543464
clan_chat_guest_channel_name=0x5A4962
clan_usernames=0x493054
clan_chat_usernames=0x4A2C58
clan_chat_guest_usernames=0x55465C
public_friend_usernames=0x24651F
player_username=0x000000

[transparent]
public_chat=0xE6E1D7
private_message_sent=0xD5A9FF
private_message_received=0xE2C0FF
friends_chat_info=0xC8B5F4
clan_chat_message=0xD2C4EE
clan_info=0xC9B6E8
clan_message=0xD7CCEA
clan_guest_info=0xBAAEC9
clan_guest_message=0xCEC4D8
autochat_message=0xD3CEC5
trade_chat_message=0xFFB2AA
server_message=0xFF938D
game_message=0xA9E2A7
examine=0xD6D0C7
filtered=0xA9A5A0
username=0xF4F0E8
private_usernames=0xE0BFFF
clan_channel_name=0xCDB9EC
clan_chat_channel_name=0xD7C4F5
clan_chat_guest_channel_name=0xBFB1CF
clan_usernames=0xE4D8F2
clan_chat_usernames=0xE8DCFA
clan_chat_guest_usernames=0xD4C9DF
public_friend_usernames=0xC9F2C7
player_username=0xFFFFFF
