displayName=Victorian Rose
compatibleVersion=1.10.5
author=W 0 N D 3 R
tags=gothic,girly,vanilla,brown,bronze,gold,pixel,art,red,gray,grey,black,dark,vintage,antique,wonder,cozy,bows,flowers,bunny,rabbit,alt,cute