package melky.resourcepacks;

import com.google.common.collect.ImmutableMultimap;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import static melky.resourcepacks.WidgetOverride.Script.*;
import static melky.resourcepacks.WidgetOverride.Children.*;
import static melky.resourcepacks.WidgetOverride.ArrayIndex.*;
import net.runelite.api.widgets.WidgetID;

@Getter
@RequiredArgsConstructor
public enum WidgetOverride
{

	GE_BORDER_BUY_INNER(GE_OFFERS_INIT, 0x5a5245, WidgetID.GRAND_EXCHANGE_GROUP_ID, GRAND_EXCHANGE_BORDER_CHILDREN_IDS, GE_BORDER[0][0]),
	GE_BORDER_BUY_OUTER(GE_OFFERS_INIT, 0x383023, WidgetID.GRAND_EXCHANGE_GROUP_ID, GRAND_EXCHANGE_BORDER_CHILDREN_IDS, GE_BORDER[0][1]),
	GE_BORDER_SELL_INNER(GE_OFFERS_INIT, 0x5a5245, WidgetID.GRAND_EXCHANGE_GROUP_ID, GRAND_EXCHANGE_BORDER_CHILDREN_IDS, GE_BORDER[0][2]),
	GE_BORDER_SELL_OUTER(GE_OFFERS_INIT, 0x383023, WidgetID.GRAND_EXCHANGE_GROUP_ID, GRAND_EXCHANGE_BORDER_CHILDREN_IDS, GE_BORDER[0][3]),

	GE_BORDER_OFFER_BUY_OFFER_FULL_INNER(GE_OFFERS_SETUP_INIT, 0x5a5245, WidgetID.GRAND_EXCHANGE_GROUP_ID, 25, 14),
	GE_BORDER_OFFER_BUY_OFFER_FULL_OUTER(GE_OFFERS_SETUP_INIT, 0x383023, WidgetID.GRAND_EXCHANGE_GROUP_ID, 25, 15),
	GE_BORDER_OFFER_BUY_OFFER_BOTTOM_INNER(GE_OFFERS_SETUP_INIT, 0x5a5245, WidgetID.GRAND_EXCHANGE_GROUP_ID, 25, 16),
	GE_BORDER_OFFER_BUY_OFFER_BOTTOM_OUTER(GE_OFFERS_SETUP_INIT, 0x383023, WidgetID.GRAND_EXCHANGE_GROUP_ID, 25, 17),
	GE_BORDER_OFFER_CHOOSE_ITEM_INNER(GE_OFFERS_SETUP_INIT, 0x5a5245, WidgetID.GRAND_EXCHANGE_GROUP_ID, 25, 23),
	GE_BORDER_OFFER_CHOOSE_ITEM_OUTER(GE_OFFERS_SETUP_INIT, 0x383023, WidgetID.GRAND_EXCHANGE_GROUP_ID, 25, 24),
	GE_BORDER_OFFER_QUANTITY_INNER(GE_OFFERS_SETUP_INIT, 0x5a5245, WidgetID.GRAND_EXCHANGE_GROUP_ID, 25, 26),
	GE_BORDER_OFFER_QUANTITY_OUTER(GE_OFFERS_SETUP_INIT, 0x383023, WidgetID.GRAND_EXCHANGE_GROUP_ID, 25, 27),
	GE_BORDER_OFFER_PRICE_INNER(GE_OFFERS_SETUP_INIT, 0x5a5245, WidgetID.GRAND_EXCHANGE_GROUP_ID, 25, 33),
	GE_BORDER_OFFER_PRICE_OUTER(GE_OFFERS_SETUP_INIT, 0x383023, WidgetID.GRAND_EXCHANGE_GROUP_ID, 25, 34),

	GE_CHATBOX_BUY_SEARCH_BORDER_INNER(GE_OFFERS_SETUP_INIT, 0x463214, WidgetID.CHATBOX_GROUP_ID, GRAND_EXCHANGE_CHAT_SEARCH_CHILDREN_IDS[0], -1),
	GE_CHATBOX_BUY_SEARCH_BORDER_OUTER(GE_OFFERS_SETUP_INIT, 0x463214, WidgetID.CHATBOX_GROUP_ID, GRAND_EXCHANGE_CHAT_SEARCH_CHILDREN_IDS[1], -1),
	GE_CHATBOX_BUY_SEARCH_BACKGROUND(GE_OFFERS_SETUP_INIT, 0x463214, WidgetID.CHATBOX_GROUP_ID, GRAND_EXCHANGE_CHAT_SEARCH_CHILDREN_IDS[2], -1),

	//depreciated
	KEYBINDS_SMALL_BACKGROUND(KEYBINDS_INIT, 0x2e281d, 121, new int[]{6, 13, 20, 27, 34, 41, 48, 55, 62, 69, 76, 83, 90, 97}, -1),
	KEYBINDS_SMALL_BORDER(KEYBINDS_INIT, 0x544834, 121, new int[]{7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98}, -1),
	KEYBINDS_MENU_BACKGROUND(KEYBINDS_OPEN_MENU, 0x2e281d, 121, 109, -1),
	KEYBINDS_MENU_BORDER(KEYBINDS_OPEN_MENU, 0x544834, 121, 110, -1),

	MAKE_ALL_BACKGROUND_HOVER(MAKE_ALL_ITEM_HOVER, 0x89785e, 270, MAKE_ALL_BACKGROUND_CHILDREN_IDS[0], MAKE_ALL_CHATBOX[0][0]),
	MAKE_ALL_BACKGROUND_CLICKED(MAKE_ALL_ITEM_OP, 0x89785e, 270, MAKE_ALL_BACKGROUND_CHILDREN_IDS[0], MAKE_ALL_CHATBOX[0][0]),
	MAKE_ALL_QUANTITY_SELECTED(MAKE_ALL_QUANTITY_DRAW, 0x89785e, 270, MAKE_ALL_BACKGROUND_CHILDREN_IDS[1], MAKE_ALL_CHATBOX[0][1]),

	ACCOUNT_MANAGEMENT_TAB_LINE(ACCOUNT_MANAGEMENT_INIT, 0x5d5848, 109, ACCOUNT_MANAGEMENT_SEPARATOR_LINE_CHILDREN_IDS, -1),

	CHATBOX_SEPERATOR_LINE(CHATBOX_BACKGROUND, 0x807660, WidgetID.CHATBOX_GROUP_ID, 54, CHATBOX_SEPARATOR_LINE[0]),

	FRIENDS_CHAT_BORDER_FULL_INNER(FRIENDS_CHAT_BUILD, 0x474745, WidgetID.FRIENDS_CHAT_GROUP_ID, 5, 1),
	FRIENDS_CHAT_BORDER_FULL_OUTER(FRIENDS_CHAT_BUILD, 0xe0e0c, WidgetID.FRIENDS_CHAT_GROUP_ID, 5, 0),
	FRIENDS_CHAT_BORDER_TOP_INNER(FRIENDS_CHAT_BUILD, 0x474745, WidgetID.FRIENDS_CHAT_GROUP_ID, 6, 1),
	FRIENDS_CHAT_BORDER_TOP_OUTER(FRIENDS_CHAT_BUILD, 0xe0e0c, WidgetID.FRIENDS_CHAT_GROUP_ID, 6, 0),

	FRIENDS_TOP_LINE_ABOVE(FRIEND_UPDATE, 0x474745, WidgetID.FRIENDS_LIST_GROUP_ID, 6, 1),
	FRIENDS_TOP_LINE_BELOW(FRIEND_UPDATE, 0xe0e0c, WidgetID.FRIENDS_LIST_GROUP_ID, 6, 0),

	IGNORE_TOP_LINE_ABOVE(IGNORE_UPDATE, 0x474745, WidgetID.IGNORE_LIST_GROUP_ID, 6, 1),
	IGNORE_TOP_LINE_BELOW(IGNORE_UPDATE, 0xe0e0c, WidgetID.IGNORE_LIST_GROUP_ID, 6, 0),

	QUEST_TAB_TABS_UNDERLINE(QUEST_TAB_TABS_DRAW, 0x5d5848, 629, 2, -1),

	XPDROPS_BORDER_INNER(XPDROPS_SHOW_PANEL, 0x5a5245, WidgetID.EXPERIENCE_DROP_GROUP_ID, EXP_DROPS_BORDER_CHILDREN_IDS[0], -1),
	XPDROPS_BORDER_OUTER(XPDROPS_SHOW_PANEL, 0x383023, WidgetID.EXPERIENCE_DROP_GROUP_ID, EXP_DROPS_BORDER_CHILDREN_IDS[1], -1),

	// Needs to be updated if an achievement diary is added
	ACHIEVEMENT_DIARY_BORDER(ACHIEVEMENT_DIARY_ENTRY_REBUILD, 0xff9933, WidgetID.ACHIEVEMENT_DIARY_GROUP_ID, 2, ACHIEVEMENT_DIARY[0]),
	ACHIEVEMENT_DIARY_PROGRESS_BORDER(ACHIEVEMENT_DIARY_ENTRY_REBUILD, 0x000000, WidgetID.ACHIEVEMENT_DIARY_GROUP_ID, 2, ACHIEVEMENT_DIARY[1]),

	KOUREND_fAVVOUR_TAB_ARCEUUS_BORDER_INNER(KOUREND_TAB_UPDATE, 0x000000, 245, KOUREND_FAVOR_CHILDREN_IDS[0][0], -1),
	KOUREND_fAVVOUR_TAB_ARCEUUS_BORDER_OUTER(KOUREND_TAB_UPDATE, 0x2000c8, 245, KOUREND_FAVOR_CHILDREN_IDS[0][1], 0),
	KOUREND_fAVVOUR_TAB_ARCEUUS_FILL(KOUREND_TAB_UPDATE, 0x2000c8, 245, KOUREND_FAVOR_CHILDREN_IDS[0][2], 0),
	KOUREND_fAVVOUR_TAB_HOSIDIUS_BORDER_INNER(KOUREND_TAB_UPDATE, 0x000000, 245, KOUREND_FAVOR_CHILDREN_IDS[1][0], -1),
	KOUREND_fAVVOUR_TAB_HOSIDIUS_BORDER_OUTER(KOUREND_TAB_UPDATE, 0x20c008, 245, KOUREND_FAVOR_CHILDREN_IDS[1][1], 0),
	KOUREND_fAVVOUR_TAB_HOSIDIUS_FILL(KOUREND_TAB_UPDATE, 0x20c008, 245, KOUREND_FAVOR_CHILDREN_IDS[1][2], 0),
	KOUREND_fAVVOUR_TAB_LOVAKENGJ_BORDER_INNER(KOUREND_TAB_UPDATE, 0x000000, 245, KOUREND_FAVOR_CHILDREN_IDS[2][0], -1),
	KOUREND_fAVVOUR_TAB_LOVAKENGJ_BORDER_OUTER(KOUREND_TAB_UPDATE, 0xc05008, 245, KOUREND_FAVOR_CHILDREN_IDS[2][1], 0),
	KOUREND_fAVVOUR_TAB_LOVAKENGJ_FILL(KOUREND_TAB_UPDATE, 0xc05008, 245, KOUREND_FAVOR_CHILDREN_IDS[2][2], 0),
	KOUREND_fAVVOUR_TAB_PISCARILIUS_BORDER_INNER(KOUREND_TAB_UPDATE, 0x000000, 245, KOUREND_FAVOR_CHILDREN_IDS[3][0], -1),
	KOUREND_fAVVOUR_TAB_PISCARILIUS_BORDER_OUTER(KOUREND_TAB_UPDATE, 0x98a0, 245, KOUREND_FAVOR_CHILDREN_IDS[3][1], 0),
	KOUREND_fAVVOUR_TAB_PISCARILIUS_FILL(KOUREND_TAB_UPDATE, 0x98a0, 245, KOUREND_FAVOR_CHILDREN_IDS[3][2], 0),
	KOUREND_fAVVOUR_TAB_SHAYZIEN_BORDER_INNER(KOUREND_TAB_UPDATE, 0x000000, 245, KOUREND_FAVOR_CHILDREN_IDS[4][0], -1),
	KOUREND_fAVVOUR_TAB_SHAYZIEN_BORDER_OUTER(KOUREND_TAB_UPDATE, 0x980810, 245, KOUREND_FAVOR_CHILDREN_IDS[4][1], 0),
	KOUREND_fAVVOUR_TAB_SHAYZIEN_FILL(KOUREND_TAB_UPDATE, 0x980810, 245, KOUREND_FAVOR_CHILDREN_IDS[4][2], 0),

	MINIGAMES_TAB_BORDER_INNER(MINIGAMES_TAB_REBUILD, 0xff981f, WidgetID.MINIGAME_TAB_ID, MINIGAMES_TAB_BORDER_CHILDREN_IDS[0], -1),
	MINIGAMES_TAB_BORDER_OUTER(MINIGAMES_TAB_REBUILD, 0x191900, WidgetID.MINIGAME_TAB_ID, MINIGAMES_TAB_BORDER_CHILDREN_IDS[1], -1),

	//depreciated
	OPTIONS_CONTROLS_MENU_BORDER_INNER(OPTIONS_TABS_SWITCH, 0x474745, WidgetID.SETTINGS_SIDE_GROUP_ID, new int[]{91, 92}, 2),
	OPTIONS_CONTROLS_MENU_BORDER_OUTER(OPTIONS_TABS_SWITCH, 0xe0e0c, WidgetID.SETTINGS_SIDE_GROUP_ID, new int[]{91, 92}, 1),
	OPTIONS_CONTROLS_DROPDOWN_BORDER_INNER(THINKBOX, 0x474745, WidgetID.SETTINGS_SIDE_GROUP_ID, 106, 1),
	OPTIONS_CONTROLS_DROPDOWN_BORDER_OUTER(THINKBOX, 0xe0e0c, WidgetID.SETTINGS_SIDE_GROUP_ID, 106, 0),

	COMBAT_CHOOSE_SPELL_BACKGROUND(AUTOCAST_SETUP, 0x000000, 201, 3, -1),
	COMBAT_CHOOSE_SPELL_INNER(AUTOCAST_SETUP, 0x726451, 201, 4, -1),
	COMBAT_CHOOSE_SPELL_OUTER(AUTOCAST_SETUP, 0x2e2b23, 201, 5, -1),

	ITEMS_KEPT_ON_DEATH_BORDER_INNER(DEATHKEEP_REDRAW, 0xe0e0c, WidgetID.KEPT_ON_DEATH_GROUP_ID, ITEMS_KEPT_ON_DEATH_CHILDREN_IDS, ITEMS_KEPT_ON_DEATH[0]),
	ITEMS_KEPT_ON_DEATH_BORDER_OUTER(DEATHKEEP_REDRAW, 0x474745, WidgetID.KEPT_ON_DEATH_GROUP_ID, ITEMS_KEPT_ON_DEATH_CHILDREN_IDS, ITEMS_KEPT_ON_DEATH[1]),

	WORLD_SWITCH_TOP_AND_BOTTOM_LINES(WORLDSWITCHER_INIT, 0x73654a, WidgetID.WORLD_SWITCHER_GROUP_ID, WORLD_SWITCHER_CHILDREN_IDS[0], -1),

	WORLD_MAP_SEARCH_BORDER_INNER(WORLDMAP_INIT, 0x474745, WidgetID.WORLD_MAP_GROUP_ID, WORLD_MAP_BORDER_CHILDREN_IDS[0], 3),
	WORLD_MAP_SEARCH_BORDER_OUTER(WORLDMAP_INIT, 0xe0e0c, WidgetID.WORLD_MAP_GROUP_ID, WORLD_MAP_BORDER_CHILDREN_IDS[0], 2),
	WORLD_MAP_PLACE_BORDER_INNER(WORLDMAP_INIT, 0x474745, WidgetID.WORLD_MAP_GROUP_ID, WORLD_MAP_BORDER_CHILDREN_IDS[1], 2),
	WORLD_MAP_PLACE_BORDER_OUTER(WORLDMAP_INIT, 0xe0e0c, WidgetID.WORLD_MAP_GROUP_ID, WORLD_MAP_BORDER_CHILDREN_IDS[1], 1),
	WORLD_MAP_PLACE_DROPDOWN_BORDER_INNER(WORLDMAP_INIT, 0x474745, WidgetID.WORLD_MAP_GROUP_ID, WORLD_MAP_BORDER_CHILDREN_IDS[2], 1),
	WORLD_MAP_PLACE_DROPDOWN_BORDER_OUTER(WORLDMAP_INIT, 0xe0e0c, WidgetID.WORLD_MAP_GROUP_ID, WORLD_MAP_BORDER_CHILDREN_IDS[2], 0),

	BANK_TAB_UNDERLINE(BANK_INIT, 0x2e2b23, WidgetID.BANK_GROUP_ID, 12, -1),
	BANK_OPTIONS_BORDER_TAB_DISPLAY_INNER(BANK_SETTINGS_OPEN, 0x2e2b23, WidgetID.BANK_GROUP_ID, 50, 13),
	BANK_OPTIONS_BORDER_TAB_DISPLAY_OUTER(BANK_SETTINGS_OPEN, 0x726451, WidgetID.BANK_GROUP_ID, 50, 14),
	BANK_OPTIONS_BORDER_BANK_FILLERS_INNER(BANK_SETTINGS_OPEN, 0x2e2b23, WidgetID.BANK_GROUP_ID, 57, 2),
	BANK_OPTIONS_BORDER_BANK_FILLERS_OUTER(BANK_SETTINGS_OPEN, 0x726451, WidgetID.BANK_GROUP_ID, 57, 1),

	KOUREND_FAVOUR_DIALOG_SEPERATOR_LINE_UPPER(ZEAH_FAVOUR_INIT, 0x2e2b23, 626, KOUREND_FAVOR_CHILDREN_IDS[10][1], -1),
	KOUREND_FAVOUR_DIALOG_SEPERATOR_LINE_LOWER(ZEAH_FAVOUR_INIT, 0x2e2b23, 626, KOUREND_FAVOR_CHILDREN_IDS[10][2], -1),
	OPTIONS_TAB_SEPERATOR_LINE(SETTINGS_SIDE_TABS_INIT, 0x5d5848, WidgetID.SETTINGS_SIDE_GROUP_ID, OPTIONS_TAB_SEPARATOR_LINE_CHILDREN_IDS, -1),
	CHANNEL_TAB_SEPERATOR_LINE(CHANNEL_TAB_INIT, 0x5d5848, 727, 2, -1),

	//new
	GE_BORDER_OFFER_BUY_OUTLINE(GE_OFFERS_SETUP_INIT, 0x5a5245, WidgetID.GRAND_EXCHANGE_GROUP_ID, GRAND_EXCHANGE_OUTLINE_CHILDREN_IDS[0], GE_BORDER[1]),
	GE_BORDER_OFFER_BUY_OUTLINE_SHADOW(GE_OFFERS_SETUP_INIT, 0x383023, WidgetID.GRAND_EXCHANGE_GROUP_ID, GRAND_EXCHANGE_OUTLINE_CHILDREN_IDS[0], GE_BORDER[2]),

	GE_BORDER_OFFER_STATUS_OUTLINE(GE_OFFERS_SETUP_INIT, 0x5a5245, WidgetID.GRAND_EXCHANGE_GROUP_ID, GRAND_EXCHANGE_OUTLINE_CHILDREN_IDS[1], GE_BORDER[3]),
	GE_BORDER_OFFER_STATUS_OUTLINE_SHADOW(GE_OFFERS_SETUP_INIT, 0x383023, WidgetID.GRAND_EXCHANGE_GROUP_ID, GRAND_EXCHANGE_OUTLINE_CHILDREN_IDS[1], GE_BORDER[4]),

	//seems to be a chat selection button without a selected/clicked variant (with the hourglass timer), ex: potion decanter in GE
	MAKE_ALL_BACKGROUND_HOVER_ALT(MAKE_ALL_ITEM_HOVER_ALT_INIT, 0x89785e, 582, MAKE_ALL_BACKGROUND_CHILDREN_IDS[2], MAKE_ALL_CHATBOX[1]),

	CHATBOX_SEPARATOR_LINE_TRANSPARENT(CHATBOX_BACKGROUND, 0x807660, WidgetID.CHATBOX_GROUP_ID, 54, CHATBOX_SEPARATOR_LINE[1]),

	KOUREND_FAVOR_POPOUT_OUTER(KOUREND_POPOUT_INIT, 0x383023, 246, KOUREND_FAVOR_CHILDREN_IDS[10][0], 0),
	KOUREND_FAVOR_POPOUT_INNER(KOUREND_POPOUT_INIT, 0x5a5245, 246, KOUREND_FAVOR_CHILDREN_IDS[10][0], 1),

	KOUREND_FAVOR_POPOUT_ARCEUUS_BORDER_INNER(KOUREND_POPOUT_INIT, 0x000000, 246, KOUREND_FAVOR_CHILDREN_IDS[5][0], -1),
	KOUREND_FAVOR_POPOUT_ARCEUUS_BORDER_OUTER(KOUREND_POPOUT_INIT, 0x2000c8, 246, KOUREND_FAVOR_CHILDREN_IDS[5][1], -1),
	KOUREND_FAVOR_POPOUT_ARCEUUS_FILL(KOUREND_POPOUT_INIT, 0x2000c8, 246, KOUREND_FAVOR_CHILDREN_IDS[5][2], -1),
	KOUREND_FAVOR_POPOUT_HOSIDIUS_BORDER_INNER(KOUREND_POPOUT_INIT, 0x000000, 246, KOUREND_FAVOR_CHILDREN_IDS[6][0], -1),
	KOUREND_FAVOR_POPOUT_HOSIDIUS_BORDER_OUTER(KOUREND_POPOUT_INIT, 0x20c008, 246, KOUREND_FAVOR_CHILDREN_IDS[6][1], -1),
	KOUREND_FAVOR_POPOUT_HOSIDIUS_FILL(KOUREND_POPOUT_INIT, 0x20c008, 246, KOUREND_FAVOR_CHILDREN_IDS[6][2], -1),
	KOUREND_FAVOR_POPOUT_LOVAKENGJ_BORDER_INNER(KOUREND_POPOUT_INIT, 0x000000, 246, KOUREND_FAVOR_CHILDREN_IDS[7][0], -1),
	KOUREND_FAVOR_POPOUT_LOVAKENGJ_BORDER_OUTER(KOUREND_POPOUT_INIT, 0xc05008, 246, KOUREND_FAVOR_CHILDREN_IDS[7][1], -1),
	KOUREND_FAVOR_POPOUT_LOVAKENGJ_FILL(KOUREND_POPOUT_INIT, 0xc05008, 246, KOUREND_FAVOR_CHILDREN_IDS[7][2], -1),
	KOUREND_FAVOR_POPOUT_PISCARILIUS_BORDER_INNER(KOUREND_POPOUT_INIT, 0x000000, 246, KOUREND_FAVOR_CHILDREN_IDS[8][0], -1),
	KOUREND_FAVOR_POPOUT_PISCARILIUS_BORDER_OUTER(KOUREND_POPOUT_INIT, 0x98a0, 246, KOUREND_FAVOR_CHILDREN_IDS[8][1], -1),
	KOUREND_FAVOR_POPOUT_PISCARILIUS_FILL(KOUREND_POPOUT_INIT, 0x98a0, 246, KOUREND_FAVOR_CHILDREN_IDS[8][2], -1),
	KOUREND_FAVOR_POPOUT_SHAYZIEN_BORDER_INNER(KOUREND_POPOUT_INIT, 0x000000, 246, KOUREND_FAVOR_CHILDREN_IDS[9][0], -1),
	KOUREND_FAVOR_POPOUT_SHAYZIEN_BORDER_OUTER(KOUREND_POPOUT_INIT, 0x980810, 246, KOUREND_FAVOR_CHILDREN_IDS[9][1], -1),
	KOUREND_FAVOR_POPOUT_SHAYZIEN_FILL(KOUREND_POPOUT_INIT, 0x980810, 246, KOUREND_FAVOR_CHILDREN_IDS[9][2], -1),

	SEED_VAULT_BOTTOM_SEPARATOR_LINE(SEED_VAULT_INIT, 0x333333, 631, 18, -1),

	TOA_RAID_PARTY_TAB_SEPARATOR_LINE(TOA_RAID_PARTY_INIT, 0x383023, 774, TOA_RAID_PARTY_SEPARATOR_LINE_CHILDREN_IDS[0], -1),
	TOA_RAID_PARTY_TAB_SEPARATOR_LINE_SHADOW(TOA_RAID_PARTY_INIT, 0x5d5848, 774, TOA_RAID_PARTY_SEPARATOR_LINE_CHILDREN_IDS[1], -1),

	YOUR_CLAN_CHAT_BORDER_FULL_INNER(YOUR_CLAN_CHAT_TAB_INIT, 0x474745, 701, 5, 1),
	YOUR_CLAN_CHAT_BORDER_FULL_OUTER(YOUR_CLAN_CHAT_TAB_INIT, 0xe0e0c, 701, 5, 0),

	OTHER_CLAN_CHAT_BORDER_FULL_INNER(OTHER_CLAN_CHAT_TAB_INIT, 0x474745, 702, 5, 1),
	OTHER_CLAN_CHAT_BORDER_FULL_OUTER(OTHER_CLAN_CHAT_TAB_INIT, 0xe0e0c, 702, 5, 0),

	CHAT_CHANNEL_SETUP_BORDER_INNER(CHAT_CHANNEL_SETUP_INIT, 0x5a5245, 94, 21, 1),
	CHAT_CHANNEL_SETUP_BORDER_OUTER(CHAT_CHANNEL_SETUP_INIT, 0x383023, 94, 21, 0),

	CHAT_CHANNEL_SETUP_BORDER_RIGHT_INNER(CHAT_CHANNEL_SETUP_INIT, 0x5a5245, 94, 23, 1),
	CHAT_CHANNEL_SETUP_BORDER_RIGHT_OUTER(CHAT_CHANNEL_SETUP_INIT, 0x383023, 94, 23, 0),

	CHAT_CHANNEL_SETUP_BORDER_TOP_INNER(CHAT_CHANNEL_SETUP_INIT, 0x5a5245, 94, 24, 1),
	CHAT_CHANNEL_SETUP_BORDER_TOP_OUTER(CHAT_CHANNEL_SETUP_INIT, 0x383023, 94, 24, 0),

	MINIGAMES_TAB_ACTIVITY_TEXT(MINIGAMES_TAB_REBUILD, 0xff9f20, WidgetID.MINIGAME_TAB_ID, 11, -1),

	MINIGAMES_TAB_DROPDOWN_INNER(MINIGAMES_TAB_REBUILD, 0xff981f, WidgetID.MINIGAME_TAB_ID, MINIGAMES_TAB_BORDER_CHILDREN_IDS[2][0], -1),
	MINIGAMES_TAB_DROPDOWN_OUTER(MINIGAMES_TAB_REBUILD, 0x191900, WidgetID.MINIGAME_TAB_ID,  MINIGAMES_TAB_BORDER_CHILDREN_IDS[2][1], -1),

	WORLD_SWITCHER_BACKGROUND_COLOR(WORLDSWITCHER_INIT, 0x73654a, WidgetID.WORLD_SWITCHER_GROUP_ID, WORLD_SWITCHER_CHILDREN_IDS[1], -1),

	QUICK_PRAYER_BACKGROUND_COLOR(QUICK_PRAYER_INIT, 0xffffff, 77, QUICK_PRAYER_BACKGROUND_CHILDREN_IDS, -1),

	COLLECTION_LOG_OUTER_BORDER(COLLECTION_LOG_INIT, 0x585040, 621, COLLECTION_LOG_BORDER_CHILDREN_IDS, -1),

	COMBAT_ACHIEVEMENTS_BOSS_BORDER_OUTER(COMBAT_ACHIEVEMENT_BOSS_INIT, 0x303030, 713, COMBAT_ACHIEVEMENTS_CHILDREN_IDS[0][0], -1),
	COMBAT_ACHIEVEMENTS_BOSS_BORDER_INNER(COMBAT_ACHIEVEMENT_BOSS_INIT, 0x5d5848, 713, COMBAT_ACHIEVEMENTS_CHILDREN_IDS[0][1], -1),

	COMBAT_ACHIEVEMENTS_BOSS_OVERVIEW_BORDER_OUTER(COMBAT_ACHIEVEMENT_BOSS_INIT, 0x303030, 713, COMBAT_ACHIEVEMENTS_CHILDREN_IDS[1][0], -1),
	COMBAT_ACHIEVEMENTS_BOSS_OVERVIEW_BORDER_INNER(COMBAT_ACHIEVEMENT_BOSS_INIT, 0x5d5848, 713, COMBAT_ACHIEVEMENTS_CHILDREN_IDS[1][1], -1),

	COMBAT_ACHIEVEMENTS_REWARDS_BORDER_OUTER(COMBAT_ACHIEVEMENT_REWARDS_INIT, 0x303030, 714, COMBAT_ACHIEVEMENTS_CHILDREN_IDS[2][0], -1),
	COMBAT_ACHIEVEMENTS_REWARDS_BORDER_INNER(COMBAT_ACHIEVEMENT_REWARDS_INIT, 0x5d5848, 714, COMBAT_ACHIEVEMENTS_CHILDREN_IDS[2][1], -1),

	CRAFTING_SILVER_JEWELLERY_HOVER(CRAFTING_SILVER_INIT, 0x9b8268, 6, CRAFT_SILVER_CHILDREN_IDS, 0),

	CRAFTING_GOLD_RINGS_HOVER(CRAFTING_GOLD_INIT, 0x9b8268, 446, CRAFT_GOLD_CHILDREN_IDS[0], 0),
	CRAFTING_GOLD_NECKLACES_HOVER(CRAFTING_GOLD_INIT, 0x9b8268, 446, CRAFT_GOLD_CHILDREN_IDS[1], 0),
	CRAFTING_GOLD_AMULETS_HOVER(CRAFTING_GOLD_INIT, 0x9b8268, 446, CRAFT_GOLD_CHILDREN_IDS[2], 0),
	CRAFTING_GOLD_BRACELETS_HOVER(CRAFTING_GOLD_INIT, 0x9b8268, 446, CRAFT_GOLD_CHILDREN_IDS[3], 0),

	SMITHING_FOCUSED_ITEM_HOVER(SMITHING_ITEMS_INIT, 0x9b8268, 312, SMITHING_CHILDREN_IDS, 0),

	STASH_UNIT_BORDER_OUTER(STASH_UNIT_INIT, 0x585040, 493, STASH_UNIT_CHILDREN_IDS[0], -1),
	STASH_UNIT_HORIZONTAL_LINE(STASH_UNIT_INIT, 0x585040, 493, STASH_UNIT_CHILDREN_IDS[1], -1),
	STASH_UNIT_LEFT_BORDER_LINE(STASH_UNIT_INIT, 0x585040, 493, STASH_UNIT_CHILDREN_IDS[2], -1),
	STASH_UNIT_LEFT_VERTICAL_LINE(STASH_UNIT_INIT, 0x585040, 493, STASH_UNIT_CHILDREN_IDS[3], -1),
	STASH_UNIT_MIDDLE_LEFT_VERTICAL_LINE(STASH_UNIT_INIT, 0x585040, 493, STASH_UNIT_CHILDREN_IDS[4], -1),
	STASH_UNIT_MIDDLE_RIGHT_VERTICAL_LINE(STASH_UNIT_INIT, 0x585040, 493, STASH_UNIT_CHILDREN_IDS[5], -1),
	STASH_UNIT_RIGHT_VERTICAL_LINE(STASH_UNIT_INIT, 0x585040, 493, STASH_UNIT_CHILDREN_IDS[6], -1),

	RUNE_POUCH_BORDER_OUTER(RUNE_POUCH_INIT, 0xff981f, WidgetID.RUNE_POUCH_GROUP_ID, 5, -1),
	RUNE_POUCH_BORDER_INNER(RUNE_POUCH_INIT, 0xebd7cc, WidgetID.RUNE_POUCH_GROUP_ID, 6, -1),
	RUNE_POUCH_INVENTORY_BORDER_OUTER(RUNE_POUCH_INIT, 0xff981f, WidgetID.RUNE_POUCH_GROUP_ID, 9, -1),
	RUNE_POUCH_INVENTORY_BORDER_INNER(RUNE_POUCH_INIT, 0xebd7cc, WidgetID.RUNE_POUCH_GROUP_ID, 10, -1),

	EXPLORERS_RING_ALCHEMY_BORDER_OUTER(EXPLORERS_RING_INIT, 0x383023, WidgetID.EXPLORERS_RING_ALCH_GROUP_ID, 5, 0),
	EXPLORERS_RING_ALCHEMY_BORDER_INNER(EXPLORERS_RING_INIT, 0x5a5245, WidgetID.EXPLORERS_RING_ALCH_GROUP_ID, 5, 1),

	LOOTING_BAG_BORDER_OUTER(LOOTING_BAG_TAB_INIT, 0x383023, WidgetID.LOOTING_BAG_GROUP_ID, 3, 0),
	LOOTING_BAG_BORDER_INNER(LOOTING_BAG_TAB_INIT, 0x5a5245, WidgetID.LOOTING_BAG_GROUP_ID, 3, 1),
	LOOTING_BAG_BANK_BORDER_OUTER(LOOTING_BAG_BANK_INIT, 0x383023, 15, 11, 0),
	LOOTING_BAG_BANK_BORDER_INNER(LOOTING_BAG_BANK_INIT, 0x5a5245, 15, 11, 1),

	BONDS_POUCH_TAB_UNDERLINE(BONDS_POUCH_INIT, 0x383023, 65, BONDS_POUCH_BORDER_CHILDREN_IDS[0], -1),
	BONDS_POUCH_TAB_UNDERLINE_SHADOW(BONDS_POUCH_INIT, 0x5a5245, 65, BONDS_POUCH_BORDER_CHILDREN_IDS[1], -1),

	BONDS_POUCH_SEPERATOR_LINE(BONDS_POUCH_INIT, 0x383023, 65, BONDS_POUCH_BORDER_CHILDREN_IDS[2][0], -1),
	BONDS_POUCH_SEPERATOR_LINE_SHADOW(BONDS_POUCH_INIT, 0x5a5245, 65, BONDS_POUCH_BORDER_CHILDREN_IDS[2][1], -1),

	ACTIVITY_ADVISOR_TAB_UNDERLINE(ACTIVITY_ADVISOR_INIT, 0x5d5848, 372, 13, 0),
	ACTIVITY_ADVISOR_TAB_UNDERLINE_SHADOW(ACTIVITY_ADVISOR_INIT, 0xe0e0c, 372, 13, 1),

	;

	private final int scriptId;
	private final int defaultColor;
	private final int widgetGroupId;
	private final int[] widgetChildIds;
	private final int[] widgetArrayIds;

	WidgetOverride(int scriptId, int defaultColor, int widgetGroupId, int[] widgetChildIds, int widgetArrayId)
	{
		this(scriptId, defaultColor, widgetGroupId, widgetChildIds, new int[]{widgetArrayId});
	}

	WidgetOverride(int scriptId, int defaultColor, int widgetGroupId, int widgetChildId, int widgetArrayId)
	{
		this(scriptId, defaultColor, widgetGroupId, widgetChildId, new int[]{widgetArrayId});
	}

	WidgetOverride(int scriptId, int defaultColor, int widgetGroupId, int widgetChildId, int[] widgetArrayIds)
	{
		this(scriptId, defaultColor, widgetGroupId, new int[]{widgetChildId}, widgetArrayIds);
	}

	static final ImmutableMultimap<Integer, WidgetOverride> scriptWidgetOverrides;

	static
	{
		ImmutableMultimap.Builder<Integer, WidgetOverride> builder = new ImmutableMultimap.Builder<>();

		for (WidgetOverride widgetOverride : values())
		{
			builder.put(widgetOverride.scriptId, widgetOverride);
		}

		scriptWidgetOverrides = builder.build();
	}

	static class Script
	{
		static final int GE_OFFERS_INIT = 803;
		static final int GE_OFFERS_SETUP_INIT = 808;
		static final int KEYBINDS_INIT = 984;
		static final int KEYBINDS_OPEN_MENU = 985;
		static final int MAKE_ALL_ITEM_HOVER = 2049;
		static final int MAKE_ALL_ITEM_OP = 2044;
		static final int MAKE_ALL_QUANTITY_DRAW = 2058;
		static final int ACCOUNT_MANAGEMENT_INIT = 2497;
		static final int CHATBOX_BACKGROUND = 923;
		static final int FRIENDS_CHAT_BUILD = 1658;
		static final int FRIEND_UPDATE = 125;
		static final int IGNORE_UPDATE = 129;
		static final int QUEST_TAB_TABS_DRAW = 2799;
		static final int XPDROPS_SHOW_PANEL = 997;
		static final int ACHIEVEMENT_DIARY_ENTRY_REBUILD = 2199;
		static final int KOUREND_TAB_UPDATE = 1229;
		static final int MINIGAMES_TAB_REBUILD = 435;
		static final int AUTOCAST_SETUP = 2098;
		static final int DEATHKEEP_REDRAW = 974;
		static final int WORLDSWITCHER_INIT = 747;
		static final int WORLDMAP_INIT = 1707;
		static final int BANK_INIT = 274;
		static final int BANK_SETTINGS_OPEN = 3276;
		static final int THINKBOX = 715;
		static final int OPTIONS_TABS_SWITCH = 529;
		static final int ZEAH_FAVOUR_INIT = 1203;
		static final int SETTINGS_SIDE_TABS_INIT = 3909;
		static final int CHANNEL_TAB_INIT = 2859;
		//new
		static final int MAKE_ALL_ITEM_HOVER_ALT_INIT = 2226;
		static final int SEED_VAULT_INIT = 742;
		static final int KOUREND_POPOUT_INIT = 1225;
		static final int QUICK_PRAYER_INIT = 244;
		static final int COLLECTION_LOG_INIT = 4080;
		static final int COMBAT_ACHIEVEMENT_BOSS_INIT = 1051;
		static final int COMBAT_ACHIEVEMENT_REWARDS_INIT = 4859;
		static final int CRAFTING_SILVER_INIT = 2939;
		static final int CRAFTING_GOLD_INIT = 429;
		static final int SMITHING_ITEMS_INIT = 2932;
		static final int STASH_UNIT_INIT = 1476;
		static final int YOUR_CLAN_CHAT_TAB_INIT = 4396;
		static final int OTHER_CLAN_CHAT_TAB_INIT = 2859;
		static final int CHAT_CHANNEL_SETUP_INIT = 1191;
		static final int TOA_RAID_PARTY_INIT = 4730;
		static final int RUNE_POUCH_INIT = 453;
		static final int EXPLORERS_RING_INIT = 273;
		static final int LOOTING_BAG_TAB_INIT = 496;
		static final int LOOTING_BAG_BANK_INIT = 490;
		static final int BONDS_POUCH_INIT = 703;
		static final int ACTIVITY_ADVISOR_INIT = 6377;
	}

	static class Children
	{
		static final int[] GRAND_EXCHANGE_BORDER_CHILDREN_IDS = {
				7, 8, 9, 10, 11, 12, 13, 14
		};
		static final int[] GRAND_EXCHANGE_OUTLINE_CHILDREN_IDS = {
				25, 15
		};
		static final int[] GRAND_EXCHANGE_CHAT_SEARCH_CHILDREN_IDS = {
				49, 48, 47
		};
		static final int[][] MAKE_ALL_BACKGROUND_CHILDREN_IDS = {
				{14, 15, 16, 17, 18, 19, 20, 21, 22, 23},//MAKE_ALL_BACKGROUND_HOVER | MAKE_ALL_BACKGROUND_CLICKED
				{7, 8, 9, 10, 11, 12},//MAKE_ALL_QUANTITY_SELECTED
				{3, 4, 5, 6}//MAKE_ALL_BACKGROUND_HOVER_2
		};
		static final int[][] KOUREND_FAVOR_CHILDREN_IDS = {
				//tab
				{6, 7, 5}, //KOUREND_FAVOR_TAB_ARCEUUS
				{9, 10, 8}, //KOUREND_FAVOR_TAB_HOSIDIUS
				{12, 13, 11}, //KOUREND_FAVOR_TAB_LOVAKENGJ
				{15, 16, 14}, //KOUREND_FAVOR_TAB_PISCARILIUS
				{18, 19, 17},//KOUREND_FAVOR_TAB_SHAYZIEN

				//popout
				{21, 22, 23}, //KOUREND_FAVOR_POPOUT_ARCEUUS
				{25, 26, 27}, //KOUREND_FAVOR_POPOUT_HOSIDIUS
				{29, 30, 31}, //KOUREND_FAVOR_POPOUT_LOVAKENGJ
				{33, 34, 35}, //KOUREND_FAVOR_POPOUT_PISCARILIUS
				{37, 38, 39}, //KOUREND_FAVOR_POPOUT_SHAYZIEN

				{4, 5, 4} //dialog lines and popout borders
		};
		static final int[] ACCOUNT_MANAGEMENT_SEPARATOR_LINE_CHILDREN_IDS = {
				2, 3, 4, 5
		};
		static final int[] OPTIONS_TAB_SEPARATOR_LINE_CHILDREN_IDS = {
				59, 60, 61, 62
		};
		static final int[][] TOA_RAID_PARTY_SEPARATOR_LINE_CHILDREN_IDS = {
				{10, 12, 14}, //TOA_RAID_PARTY_TAB_SEPARATOR_LINE
				{11, 13, 15} //TOA_RAID_PARTY_TAB_SEPARATOR_LINE_SHADOW
		};
		static final int[][] EXP_DROPS_BORDER_CHILDREN_IDS = {
				{8, 13},//XPDROPS_BORDER_INNER
				{7, 12}//XPDROPS_BORDER_OUTER
		};
		static final int[][] MINIGAMES_TAB_BORDER_CHILDREN_IDS = {
				{7, 8, 9, 13, 14}, //MINIGAMES_TAB_BORDER_INNER
				{10, 15}, //MINIGAMES_TAB_BORDER_OUTER
				{20, 21} //MINIGAMES_TAB_DROPDOWN_INNER | MINIGAMES_TAB_DROPDOWN_OUTER
		};
		static final int[] ITEMS_KEPT_ON_DEATH_CHILDREN_IDS = {
				4, 5, 12
		};
		static final int[][] WORLD_SWITCHER_CHILDREN_IDS = {
				{7, 8}, //WORLD_SWITCHER_TOP_AND_BOTTOM_LINES
				{9} //WORLD_SWITCHER_BACKGROUND_COLOR
		};
		static final int[] WORLD_MAP_BORDER_CHILDREN_IDS = {
				25, 26, 33
		};
		static final int[] QUICK_PRAYER_BACKGROUND_CHILDREN_IDS = {
				1, 2, 3
		};
		static final int[] COLLECTION_LOG_BORDER_CHILDREN_IDS = {
				21, 30, 38
		};
		static final int[][] COMBAT_ACHIEVEMENTS_CHILDREN_IDS = {
				{18, 19}, //COMBAT_ACHIEVEMENTS_BOSS_BORDER
				{31, 32}, //COMBAT_ACHIEVEMENTS_BOSS_OVERVIEW_BORDER
				{8, 9} //COMBAT_ACHIEVEMENTS_REWARDS_BORDER
		};
		static final int[] CRAFT_GOLD_CHILDREN_IDS = {
				7, 22, 36, 49
		};
		static final int[] SMITHING_CHILDREN_IDS = {
				9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35
		};
		static final int[] CRAFT_SILVER_CHILDREN_IDS = {
				7, 8, 9, 11, 12, 13, 15, 16, 17, 19, 20, 21
		};
		static final int[] STASH_UNIT_CHILDREN_IDS = {
				16, 17, 19, 21, 23, 25, 27
		};
		static final int[][] BONDS_POUCH_BORDER_CHILDREN_IDS = {
				{3, 5},//BONDS_POUCH_TAB_UNDERLINE
				{4, 6},//BONDS_POUCH_TAB_UNDERLINE_SHADOW
				{15, 16},//BONDS_POUCH_SEPERATOR_LINE | BONDS_POUCH_SEPERATOR_LINE_SHADOW
		};

	}

	static class ArrayIndex
	{
		static final int[][] GE_BORDER = {
				{0, 3, 1, 4}, //GE_BORDER_BUY_INNER/GE_BORDER_BUY_OUTER || GE_BORDER_SELL_INNER/GE_BORDER_SELL_OUTER
				{15, 17, 24, 27, 34},//GE_BORDER_OFFER_BUY_OUTLINE
				{14, 16, 23, 26, 33},//GE_BORDER_OFFER_BUY_OUTLINE_SHADOW
				{1, 3, 10, 13, 20},//GE_BORDER_OFFER_STATUS_OUTLINE
				{0, 2, 9, 12, 19},//GE_BORDER_OFFER_STATUS_OUTLINE_SHADOW
		};
		static final int[][] MAKE_ALL_CHATBOX = {
				{29, 0},//MAKE_ALL_BACKGROUND_HOVER / MAKE_ALL_BACKGROUND_CLICKED
				{0, 1, 2, 3, 4, 5, 6, 7, 8, 9} //MAKE_ALL_BACKGROUND_HOVER_2
		};
		static final int[][] CHATBOX_SEPARATOR_LINE = {
				{0}, //CHATBOX_SEPARATOR_LINE_FIXED
				{1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39} //CHATBOX_SEPARATOR_LINE_TRANSPARENT
		};
		static final int[][] ACHIEVEMENT_DIARY = {
				{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}, //ACHIEVEMENT_DIARY_BORDER
				{15, 27, 39, 51, 63, 75, 87, 99, 111, 123, 135, 147} //ACHIEVEMENT_DIARY_PROGRESS_BORDER border
		};
		static final int[][] ITEMS_KEPT_ON_DEATH = {
				{0, 4},//ITEMS_KEPT_ON_DEATH_BORDER_INNER
				{1, 5}//ITEMS_KEPT_ON_DEATH_BORDER_OUTER
		};
	}
}
